Repository WattRex/Regenerative-Battery-Cycler, pull requests merged in 2023-08, with the labels that each got.

#119 feature/MID_DABS Added adc to temp conversion using look up table
  firmware/Sources/MID/MID_DABS/mid_dabs.c
  firmware/Sources/MID/MID_DABS/mid_dabs.h
Labels: enhancement

#120 Feature/app iface
  firmware/Sources/APP/APP_IFACE/app_iface.c
Labels: enhancement

#121 feature/APP_SALG
  firmware/Sources/APP/APP_SALG/app_salg.c
Labels: enhancement

#123 Minor change to make it work in dabs init
  firmware/Sources/MID/MID_DABS/mid_dabs.c
Labels: bug

#122 feature/APP_SALG
  firmware/Sources/APP/APP_SALG/app_salg.h
Labels: bug

#125 Feature/app ctrl
  firmware/Sources/APP/APP_CTRL/app_ctrl.c
Labels: bug

#124 Feature/mid dabs
  firmware/Sources/MID/MID_DABS/mid_dabs.c
Labels: enhancement

#127 Delete magic numbers in STS
  firmware/Sources/HAL/HAL_STS/hal_sts.c
Labels: enhancement

#126 MID_PWR
  firmware/Sources/MID/MID_PWR/mid_pwr.c
Labels: enhancement

#128 Update HW_limits epc_conf.c
  firmware/project_config/EPC_CONF/epc_conf.c
Labels: enhancement

#129 Feature/qa
  firmware/Sources/APP/APP_CTRL/app_ctrl.c
  firmware/Sources/APP/APP_CTRL/app_ctrl.h
  firmware/Sources/APP/APP_IFACE/app_iface.c
  firmware/Sources/APP/APP_IFACE/app_iface.h
  firmware/Sources/APP/APP_SALG/app_salg.c
  firmware/Sources/APP/APP_SALG/app_salg.h
  firmware/Sources/HAL/HAL_ADC/hal_adc.c
  firmware/Sources/HAL/HAL_ADC/hal_adc.h
  firmware/Sources/HAL/HAL_CAN/hal_can.c
  firmware/Sources/HAL/HAL_CAN/hal_can.h
  firmware/Sources/HAL/HAL_GPIO/hal_gpio.c
  firmware/Sources/HAL/HAL_GPIO/hal_gpio.h
  firmware/Sources/HAL/HAL_PWM/hal_pwm.c
  firmware/Sources/HAL/HAL_PWM/hal_pwm.h
  firmware/Sources/HAL/HAL_STS/hal_sts.c
  firmware/Sources/HAL/HAL_STS/hal_sts.h
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
  firmware/Sources/HAL/HAL_SYS/hal_sys.h
  firmware/Sources/HAL/HAL_TMR/hal_tmr.c
  firmware/Sources/HAL/HAL_TMR/hal_tmr.h
  firmware/Sources/HAL/HAL_WDG/hal_wdg.c
  firmware/Sources/HAL/HAL_WDG/hal_wdg.h
  firmware/Sources/MID/MID_COMM/mid_comm.c
  firmware/Sources/MID/MID_COMM/mid_comm.h
  firmware/Sources/MID/MID_DABS/mid_dabs.c
  firmware/Sources/MID/MID_DABS/mid_dabs.h
  firmware/Sources/MID/MID_PWR/mid_pwr.c
  firmware/Sources/MID/MID_PWR/mid_pwr.h
  firmware/Sources/MID/MID_REG/mid_reg.c
  firmware/Sources/MID/MID_REG/mid_reg.h
  firmware/Sources/Test/HAL/hal_adc_test.c
  firmware/Sources/Test/HAL/hal_adc_test.h
  firmware/Sources/Test/HAL/hal_can_test.c
  firmware/Sources/Test/HAL/hal_can_test.h
  firmware/Sources/Test/HAL/hal_gpio_test.c
  firmware/Sources/Test/HAL/hal_gpio_test.h
  firmware/Sources/Test/HAL/hal_pwm_test.c
  firmware/Sources/Test/HAL/hal_pwm_test.h
  firmware/Sources/Test/HAL/hal_sts_test.c
  firmware/Sources/Test/HAL/hal_sts_test.h
  firmware/Sources/Test/HAL/hal_tmr_test.c
  firmware/Sources/Test/HAL/hal_tmr_test.h
  firmware/Sources/Test/HAL/hal_wdg_test.c
  firmware/Sources/Test/HAL/hal_wdg_test.h
  firmware/Sources/Test/MID/mid_comm_test.c
  firmware/Sources/Test/MID/mid_comm_test.h
  firmware/Sources/Test/MID/mid_dabs_test.c
  firmware/Sources/Test/MID/mid_dabs_test.h
  firmware/Sources/Test/MID/mid_pwr_test.c
  firmware/Sources/Test/MID/mid_pwr_test.h
  firmware/Sources/Test/test.c
  firmware/Sources/Test/test.h
  firmware/project_config/EPC_CONF/epc_conf.c
  firmware/project_config/EPC_CONF/epc_conf.h
Labels: documentation

#132 minor change in epc conf comments
  firmware/project_config/EPC_CONF/epc_conf.c
Labels: enhancement

#133 Change in hw version initilization if there is STS sensor
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
Labels: enhancement

#135 mid reg
  firmware/Sources/MID/MID_REG/mid_reg.h
Labels: enhancement

#134 feature/fw
  firmware/project_config/EPC_CONF/epc_conf.c
Labels: enhancement

#136 APP CTRL
  firmware/Sources/APP/APP_CTRL/app_ctrl.c
Labels: enhancement

#137 Feature/mid dabs
  firmware/Sources/MID/MID_DABS/mid_dabs.c
Labels: enhancement

#141 Feature/fw
  firmware/STM32/Core/Src/i2c.c
  firmware/project_config/EPC_CONF/epc_conf.h
Labels: enhancement

#142 Update SOA units
  firmware/Sources/MID/MID_PWR/mid_pwr.c
Labels: enhancement

#138 Feature/mid reg
  firmware/Sources/MID/MID_REG/mid_reg.h
Labels: enhancement

#139 Feature/app iface
  firmware/Sources/APP/APP_IFACE/app_iface.c
Labels: enhancement

#148 Minor change, wait mode only acepts time limit
  firmware/Sources/APP/APP_IFACE/app_iface.c
Labels: enhancement

#149 Feature/hal imports
  firmware/Sources/HAL/HAL_ADC/hal_adc.c
  firmware/Sources/HAL/HAL_ADC/hal_adc.h
  firmware/Sources/HAL/HAL_CAN/hal_can.c
  firmware/Sources/HAL/HAL_PWM/hal_pwm.c
  firmware/Sources/HAL/HAL_TMR/hal_tmr.h
  firmware/Sources/HAL/HAL_WDG/hal_wdg.h
Labels: enhancement
