Repository WattRex/Regenerative-Battery-Cycler, pull requests merged in 2023-07, with the labels that each got.

#100 feature/MID_PWR Added define to convert to dW from mSI
  firmware/Sources/MID/MID_PWR/mid_pwr.c
  firmware/Sources/MID/MID_PWR/mid_pwr.h
Labels: enhancement

#105 feature/fw
  firmware/project_config/.cproject
  firmware/project_config/.project
  firmware/project_config/EPC_CONF/epc_conf.c
  firmware/project_config/EPC_CONF/epc_conf.h
  firmware/project_config/epc.ioc
Labels: enhancement

#109 feature/HAL_SYS
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
Labels: enhancement

#106 feature/MID_DABS
  firmware/Sources/MID/MID_DABS/mid_dabs.c
Labels: enhancement

#102 feature/MID_REG
  firmware/Sources/MID/MID_REG/mid_reg.h
Labels: enhancement

#101 feature/MID_COMM
  firmware/Sources/MID/MID_COMM/mid_comm.c
  firmware/Sources/MID/MID_COMM/mid_comm.h
  firmware/Sources/Test/CAN_MESSAGES_TRANSMIT.xmt
Labels: enhancement

#103 feature/APP_IFACE
  firmware/Sources/APP/APP_IFACE/app_iface.c
Labels: enhancement

#104 feature/APP_CTRL
  firmware/Sources/APP/APP_CTRL/app_ctrl.c
Labels: enhancement

#107 Feature/app salg
  firmware/Sources/APP/APP_SALG/app_salg.c
  firmware/Sources/APP/APP_SALG/app_salg.h
Labels: enhancement, good first issue

#114 feature/fw
  firmware/project_config/EPC_CONF/epc_conf.c
Labels: enhancement

#110 HAL_SYS
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
Labels: enhancement

#111 MID_DABS
  firmware/Sources/MID/MID_DABS/mid_dabs.c
Labels: enhancement

#112 MID_REG
  firmware/Sources/MID/MID_REG/mid_reg.h
Labels: enhancement

#113 Feature/app iface
  firmware/Sources/APP/APP_IFACE/app_iface.c
Labels: enhancement

#115 Feature/app ctrl
  firmware/Sources/APP/APP_CTRL/app_ctrl.c
Labels: enhancement

#116 Add license
  LICENSE.md
Labels: documentation

#117 Feature/app iface
  firmware/Sources/APP/APP_IFACE/app_iface.c
Labels: enhancement
