Repository WattRex/Regenerative-Battery-Cycler, pull requests merged in 2023-05, with the labels that each got.

#22 Update README.md
  README.md
  firmware/README.md
Labels: documentation

#26 headers fixed. Includes ordered in APP_SALG
  firmware/Sources/APP/APP_SALG/app_salg.c
  firmware/Sources/APP/APP_SALG/app_salg.h
Labels: QA

#27 QA to Test files
  firmware/Sources/Test/test.c
  firmware/Sources/Test/test.h
Labels: QA

#30 Integration of HAL_TMR
  firmware/Sources/HAL/HAL_TMR/hal_tmr.c
  firmware/Sources/HAL/HAL_TMR/hal_tmr.h
  firmware/Sources/Test/HAL/hal_tmr_test.c
  firmware/Sources/Test/HAL/hal_tmr_test.h
Labels: good first issue
