Repository WattRex/Regenerative-Battery-Cycler, pull requests merged in 2023-06, with the labels that each got.

#29 Feature/hal can
  firmware/Sources/HAL/HAL_CAN/hal_can.c
  firmware/Sources/HAL/HAL_CAN/hal_can.h
  firmware/Sources/Test/HAL/hal_can_test .md
  firmware/Sources/Test/HAL/hal_can_test.c
  firmware/Sources/Test/HAL/hal_can_test.h
  firmware/Sources/Test/HAL/hal_can_test.md
Labels: internal

#41 Enhancement HAL_TMR
  firmware/Sources/HAL/HAL_TMR/hal_tmr.c
Labels: enhancement

#39 Public and private functions
  firmware/Sources/Test/HAL/hal_gpio_test.c
  firmware/Sources/Test/HAL/hal_gpio_test.h
Labels: QA

#40 WDG integration
  firmware/Sources/HAL/HAL_WDG/hal_wdg.c
  firmware/Sources/HAL/HAL_WDG/hal_wdg.h
  firmware/Sources/Test/HAL/hal_wdg_test.c
  firmware/Sources/Test/HAL/hal_wdg_test.h
Labels: good first issue

#45 Add PWM configuration
  firmware/STM32/Core/Inc/main.h
  firmware/STM32/Core/Inc/stm32f3xx_hal_conf.h
  firmware/STM32/Core/Inc/stm32f3xx_it.h
  firmware/STM32/Core/Src/adc.c
  firmware/STM32/Core/Src/dma.c
  firmware/STM32/Core/Src/hrtim.c
  firmware/STM32/Core/Src/iwdg.c
  firmware/STM32/Core/Src/stm32f3xx_it.c
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
  firmware/Sources/Test/HAL/hal_sts_test.c
  firmware/Sources/Test/test.c
  firmware/project_config/.cproject
  firmware/project_config/.project
  firmware/project_config/EPC_CONF/epc_conf.h
  firmware/project_config/epc.ioc
Labels: enhancement, internal

#49 Feature/doc_mid_reg
  doc/uEPC.simp
Labels: documentation

#47 Feature/hal pwm 2
  firmware/Sources/HAL/HAL_PWM/hal_pwm.c
  firmware/Sources/HAL/HAL_PWM/hal_pwm.h
  firmware/Sources/Test/HAL/hal_pwm_test.c
  firmware/Sources/Test/HAL/hal_pwm_test.h
  firmware/Sources/Test/HAL/hal_pwm_test.md
Labels: good first issue

#51 Feature/doc_MID_DABS
  doc/uEPC.simp
Labels: documentation

#50 included extern definition of global variable EPC_ST_ERR_COUNTER
  firmware/STM32/Core/Src/main.c
  firmware/Sources/HAL/HAL_CAN/hal_can.c
  firmware/Sources/HAL/HAL_GPIO/hal_gpio.c
  firmware/Sources/HAL/HAL_STS/hal_sts.c
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
  firmware/Sources/HAL/HAL_TMR/hal_tmr.c
  firmware/Sources/HAL/HAL_WDG/hal_wdg.c
Labels: enhancement

#48 Feature/mid reg
  firmware/Sources/MID/MID_REG/mid_reg.c
  firmware/Sources/MID/MID_REG/mid_reg.h
Labels: good first issue

#53 Integration of ADC + DMA
  firmware/STM32/Core/Inc/main.h
  firmware/STM32/Core/Src/adc.c
  firmware/STM32/Core/Src/hrtim.c
  firmware/STM32/Core/Src/iwdg.c
  firmware/STM32/Core/Src/main.c
  firmware/STM32/Core/Src/stm32f3xx_it.c
  firmware/STM32/Core/Src/tim.c
  firmware/Sources/Test/test.c
  firmware/project_config/EPC_CONF/epc_conf.h
  firmware/project_config/epc.ioc
Labels: enhancement, good first issue

#54 ADC1&2 working with DMA and timer 2 and 3
  firmware/Sources/HAL/HAL_ADC/hal_adc.c
  firmware/Sources/HAL/HAL_ADC/hal_adc.h
  firmware/Sources/Test/HAL/hal_adc_test.c
  firmware/Sources/Test/HAL/hal_adc_test.h
Labels: enhancement

#57 Feature/hal sys
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
  firmware/Sources/HAL/HAL_SYS/hal_sys.h
Labels: good first issue

#63 Enhancement Feature/hal_can Add/Del filters and return error message
  firmware/Sources/HAL/HAL_CAN/hal_can.c
  firmware/Sources/HAL/HAL_CAN/hal_can.h
  firmware/Sources/Test/HAL/hal_can_test.c
Labels: enhancement

#64 MID_REG_errorStatus_s changed to MID_REG_error_status_s
  firmware/Sources/MID/MID_REG/mid_reg.h
Labels: bug

#66 Feature/fw
  firmware/Sources/APP/APP_SALG/app_salg.c
  firmware/Sources/APP/APP_SALG/app_salg.h
  firmware/Sources/HAL/HAL_SYS/hal_sys.c
  firmware/Sources/MID/MID_REG/mid_reg.h
  firmware/Sources/Test/test.c
  firmware/project_config/EPC_CONF/epc_conf.c
  firmware/project_config/EPC_CONF/epc_conf.h
Labels: enhancement

#67 Feature/fw CHANGE PERIODIC STRUCT
  firmware/Sources/MID/MID_REG/mid_reg.h
  firmware/project_config/EPC_CONF/epc_conf.c
  firmware/project_config/EPC_CONF/epc_conf.h
Labels: enhancement

#68 Feature/hal can Fixed error in DelFilters
  firmware/Sources/HAL/HAL_CAN/hal_can.c
Labels: bug

#52 Feature/mid dabs
  firmware/Sources/MID/MID_DABS/mid_dabs.c
  firmware/Sources/MID/MID_DABS/mid_dabs.h
  firmware/Sources/Test/MID/mid_dabs_test.c
  firmware/Sources/Test/MID/mid_dabs_test.h
  firmware/Sources/Test/MID/mid_dabs_test.md
Labels: good first issue

#69 Feature/mid comm
  firmware/Sources/MID/MID_COMM/mid_comm.c
  firmware/Sources/MID/MID_COMM/mid_comm.h
  firmware/Sources/Test/MID/mid_comm_test.c
  firmware/Sources/Test/MID/mid_comm_test.h
Labels: good first issue

#70 Feature/fw
  firmware/Sources/HAL/HAL_ADC/hal_adc.c
  firmware/Sources/HAL/HAL_ADC/hal_adc.h
  firmware/Sources/Test/HAL/hal_pwm_test.c
  firmware/Sources/Test/HAL/hal_tmr_test.c
  firmware/Sources/Test/test.c
Labels: enhancement

#71 Naming convention
  firmware/Sources/MID/MID_COMM/mid_comm.c
  firmware/Sources/MID/MID_COMM/mid_comm.h
  firmware/Sources/MID/MID_DABS/mid_dabs.c
  firmware/Sources/Test/MID/mid_comm_test.c
  firmware/Sources/Test/MID/mid_dabs_test.c
  firmware/project_config/.cproject
  firmware/project_config/.project
  firmware/project_config/EPC_CONF/epc_conf.h
Labels: enhancement

#72 Implement executive cycling on salg
  firmware/Sources/APP/APP_SALG/app_salg.c
  firmware/Sources/APP/APP_SALG/app_salg.h
Labels: good first issue

#73 Add interface of APP_IFACE for CI process
  firmware/Sources/APP/APP_IFACE/app_iface.c
  firmware/Sources/APP/APP_IFACE/app_iface.h
  firmware/Sources/MID/MID_DABS/mid_dabs.c
Labels: enhancement

#74 Feature/hal pwm change duty units
  firmware/Sources/HAL/HAL_PWM/hal_pwm.c
  firmware/Sources/HAL/HAL_PWM/hal_pwm.h
  firmware/Sources/Test/HAL/hal_pwm_test.c
Labels: enhancement

#97 feature/HAL_TMR Fixed condition in TmrDelay
  firmware/Sources/HAL/HAL_TMR/hal_tmr.c
Labels: bug

#94 feature/fw Update register periodic time min and CAN ID
  firmware/project_config/EPC_CONF/epc_conf.c
  firmware/project_config/EPC_CONF/epc_conf.h
Labels: documentation, enhancement

#92 Feature/app ctrl
  firmware/Sources/APP/APP_CTRL/app_ctrl.c
  firmware/Sources/APP/APP_CTRL/app_ctrl.h
Labels: good first issue

#96 Feature/app iface
  firmware/Sources/APP/APP_IFACE/app_iface.c
  firmware/Sources/APP/APP_IFACE/app_iface.h
  firmware/Sources/APP/APP_SALG/app_salg.c
  firmware/Sources/MID/MID_COMM/mid_comm.c
  firmware/Sources/MID/MID_COMM/mid_comm.h
  firmware/Sources/Test/MID/mid_comm_test.c
Labels: documentation, enhancement

#93 feature/MID_COMM Update, addfilters ok +example pcanviewer
  firmware/Sources/MID/MID_COMM/mid_comm.c
  firmware/Sources/MID/MID_COMM/mid_comm.h
  firmware/Sources/Test/CAN_MESSAGES_TRANSMIT.xmt
  firmware/Sources/Test/MID/mid_comm_test.c
Labels: enhancement

#98 feature/HAL_PWM Update definition for magic number MIN_PWM
  firmware/Sources/HAL/HAL_PWM/hal_pwm.c
  firmware/Sources/HAL/HAL_PWM/hal_pwm.h
Labels: enhancement
